### ISSUE TITLE
Exporting Archive Takes Too Long

### ISSUE THREAD

**Issue by dirkniblick** [rundeck/rundeck-cli#121]
I've created a backup script to protect my Rundeck environment.  Part of it uses the CLI to export an archive of each project:
```
/usr/bin/rd projects archives export -f ${PROJ}.zip -i all -p $PROJ
```
My primary project is (somewhat?) beefy.  It has almost 60000 executions from 58 jobs although my rundeckdb.mv.db is only about 350MB (is that big?).  Anyhow, this command never seems to finish.  I mean, the last time it ran successfully, it took about 6 hours.  I tried changing the -i option, but all I get is:
```
Input error for [export]: Cannot use --include: [jobs] with API < 19
You can use: "export help" to get help.
```
When I try doing this via the web interface by disabling the executions option, the archive returned in seconds.  Leaving set to "all"...it's at 3% after about 10 minutes.  So, how do I get the rd-cli to do a "partial" archive export?  I have been unable to determine how to "upgrade" my API, however I'm running the newest Rundeck RPMs:
```
Installed Packages
rundeck.noarch                                      2.9.3-1.37.GA                               @rundeck-release-bintray
rundeck-cli.noarch                                  1.0.17-1                                    @rundeck-release-bintray
rundeck-config.noarch                               2.9.3-1.37.GA                               @rundeck-release-bintray
```

**Comment by gschueler** [comment]
The client uses a default API version of 18 right now, but supports API v19.

if your RD_URL is `http://server:port/rundeck` for rundeck, then you can set the api version to 19 by changing that to `http://server:port/rundeck/api/19`

**Comment by dirkniblick** [comment]
That worked.  Thank you!

**Comment by gschueler** [comment]
Closing this issue, I filed a new one about having a smarter way to use the latest common API version: https://github.com/rundeck/rundeck-cli/issues/126
