### ISSUE TITLE
How to perform an scm export?

### ISSUE THREAD

**Issue by dandunckelman** [rundeck/rundeck-cli#122]
# Summary
I'm trying to figure out how to use the SCM Export plugin so my jobs will be pushed to an external git repo.

# Problem
- I was able to enable the `Git Export` plugin via GUI, but I'm unsure of my next steps.
- The furthest I could get was this:
  - Get a project's SCM status:

        $ rd projects scm status --project Infrastructure --integration export

        synchState: EXPORT_NEEDED                                                       
        message: Some changes have not been committed                                   
        actions:                                                                        
          project-commit                                                                

  - Get the entire list of the project's jobs (put it into a space-delimited list)

        $ JOB_IDS=`rd jobs list --project Infrastructure --outformat "%id" | head -n -1 | xargs echo`
  - Perform the project-commit action

        $ rd projects scm perform --project Infrastructure \
            --integration export \
            --action project-commit \
            --job $JOB_IDS \
            --field message=test committerName=test

        Action project-commit failed                                      
        Required user info field was not set: committerName               
        committerName: Required user info field was not set: committerName

What am I doing wrong?

**Comment by dandunckelman** [comment]
@gschueler thanks for taking this on.  Please let me know if you need more info.

**Comment by gschueler** [comment]
hi @dandunckelman the `committerName` is actually a configuration value in the Git SCM Export plugin's setup that needs to be set.  It can be set to `${user.firstName} ${user.lastName}` or
`${user.fullName}` to expand as the name of the committing user.  The values are taken from the user's Profile values set in the Rundeck GUI.  If the user's Profile is not configured, it may fail with that result.  In the Rundeck GUI when it has this kind of failure, it prompts you to go to the user Profile page and enter a name and email.

**Comment by dandunckelman** [comment]
@gschueler thanks!

I didn't realize it (tho it is obvious), but the `rd` CLI was pulling user creds from `~/.rd/rd.conf`, which referenced a user w/o email/name set.

After updating those fields, I got this:

```
# Action project-commit was successful.                   
# Result: SCM export Action was Successful: project-commit
```

Quick question:  when I first came across this plugin, I assumed that it automatically would push to the git repo when job changes are made (akin to a `git commit`).  But AFAIK, that's not how it works.

Instead, it gives visual cues in the UI that a job needs to be committed, and I can do that via UI or the CLI.

Is there also a reverse mechanism, where it will pull changes from the repo when updates have been made to the remote repo?

**Comment by gschueler** [comment]
the plugin can either 'fetch' or 'synch' from the remote.  'fetch' is the same as git fetch and is only presented in the GUI if you disable the 'automatic fetch'.  'synch' will merge or rebase the local branch with any fetched changes.  you can specify how in the inputs to the action.

**Comment by dandunckelman** [comment]
@gschueler I ended up creating a job that runs this daily:

```
#!/bin/bash
for PROJECT in $RD_OPTION_PROJECTS; do
    STATUS=`rd projects scm status --project $PROJECT --integration export`

    echo "Current status for $PROJECT:"
    echo "$STATUS"
    echo ""

    SYNCH_STATE=`echo "$STATUS" | grep synchState | sed "s/synchState: \(.*\)$/\1/"`
    
    if [ "$SYNCH_STATE" == "EXPORT_NEEDED" ]; then
        echo "Because synchState is $SYNCH_STATE, we must commit/push to the remote repo"
    
        ACTION=`echo "$STATUS" | grep -A 1 actions | tail -n 1 | awk '{$1=$1};1'`
        JOB_IDS=`rd jobs list --project $PROJECT --outformat "%id" | head -n -1 | xargs echo`
    
        echo "Performing a '$ACTION'..."
        rd projects scm perform --project $PROJECT \
            --integration export \
            --action $ACTION \
            --job $JOB_IDS \
            --field message="Daily sync"
    
        echo "Performing a 'project-push'..."
        rd projects scm perform --project $PROJECT --integration export --action project-push
    else
        echo "What should we do? Nothing?"
    fi
done
```

Thanks for the help.
