### ISSUE TITLE
Artifacts not found for release v1.0.18

### ISSUE THREAD

**Issue by luisjaviersanz** [rundeck/rundeck-cli#125]
I'm currently using Rundeck CLI and I have automated to process of retrieving the tool as part of my CI pipeline, but I'm not able to get the latest one because it seems the artifacts (zip, jar, rpm and deb files) have not been generated.

Is it correct or a defect? If so, is there a way to fix it?

Thanks in advance!

Regards.

**Comment by luisjaviersanz** [comment]
@gschueler, any update on this issue?

Thanks!

**Comment by gschueler** [comment]
!! weird, I don't know why that occurred.  It seems all of the artifacts made it to bintray, but not to the Github Releases.  the release happens via Travis-ci, so I'll have to figure out what went wrong.

**Comment by gschueler** [comment]
made a tweak to travis.yaml, and did a new release.  lmk if that works for you

**Comment by luisjaviersanz** [comment]
I've just checked it out and it started to work again.

Thanks, @gschueler!
