### ISSUE TITLE
Update to use latest API version by default, or negotiate w/ server

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck-cli#126]
Some features only work on newer API version with Rundeck.  Some clients are running older version of rundeck.

We should keep the "default" API version at the latest supported level.  If the server doesn't support that newer version, the User should define `RD_URL=http://server/api/X` where X is the latest supported version for their server.

Ideally, if using a bare `RD_URL=http://server/rundeck` URL (without specifying API version), `rd` should detect the latest supported API version by the Rundeck server and then use the latest specific API version that is commonly supported.

**Comment by Alveel** [comment]
Hi, sorry for reopening this issue, but it seems the auto-downgrading functionality doesn't properly work.

Using Rundeck 2.3.9 (API version 20) and rundeck-cli 1.0.20, with "export RD_API_DOWNGRADE=true" in rd.conf, I still get
`Error: Unsupported API Version "21". API Request: /api/21/project/$project/jobs. Reason: Current version: 20`

Setting the RD_URL to include `/api/20` works, though 😃

**Comment by gschueler** [comment]
@Alveel ok, thanks I will try to reproduce it

**Comment by gschueler** [comment]
@Alveel which version do you have? did you mean 2.9.3?

**Comment by Alveel** [comment]
@gschueler correct, I am on version 2.9.3-1, sorry :)

**Comment by gschueler** [comment]
figured ;)  I discovered the issue, not all of the api calls were using the same interface to do so, so it wasn't hooking into the downgrade mechanism
