### ISSUE TITLE
Allow config file settings to be overridden by environment variables

### ISSUE THREAD

**Issue by dandunckelman** [rundeck/rundeck-cli#130]
# Summary
Similar to #72, it would be nice to have a default config file and the ability to override any of those values via environment variables.

## Example
I have a `.rd/rd.conf` file like this:

```
export RD_URL=http://rundeck-01.ta.local:4440/api/19
export RD_USER=admin                                    
export RD_PASSWORD=mypass
export RD_COLOR=0
```

But there are times when I'd like to run commands against our "standby" instance while on the "active" one.  Ideally, I'd be able to do this:

```
RD_URL=http://rundeck-02.ta.local:4440/api/19 rd system info
```

but this currently doesn't work.  It always uses the value in the config file.

**Comment by gschueler** [comment]
hmm, since it is simply a bash script, you could try changing `~/.rd/rd.conf` to:

    export RD_URL=${RD_URL:-http://rundeck-01.ta.local:4440/api/19}
    export RD_USER=${RD_USER:-admin}                                    
    export RD_PASSWORD=${RD_PASSWORD:-mypass}
    export RD_COLOR=${RD_COLOR:-0}
    #etc

This will not alter the values you have already exported

**Comment by dandunckelman** [comment]
@gschueler thanks!  That works as expected.
