### ISSUE TITLE
ec2 nodes not displaying all tags

### ISSUE THREAD

**Issue by jjethwa** [rundeck/rundeck-cli#140]
We're using the ec2 nodes plugin: https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin to pull up nodes for our Rundeck projects.  When using the CLI utility to list the nodes, ec2 nodes only return ec2 in the tag list and nothing else.  Nodes added to the project resources.xml show all tags.  Tags display correctly in the web interface and queries against them (UI and CLI utility) work properly.

Example usage:
```
./rd-1.0.22/bin/rd nodes list -p testproject -% "%nodename %tags"
```

I've tried the listing with and without the verbose flag as well.

**Comment by gschueler** [comment]
is the data present in the response if your use `RD_DEBUG=3` ?

**Comment by jjethwa** [comment]
Unfortunately, no 😞

**Comment by gschueler** [comment]
Is this still a problem? have you tried recent versions of rundeck? (one nodes issue was resolved in 2.10.5

**Comment by jjethwa** [comment]
Hi @gschueler 

Sorry, I forgot about this issue.  Yes, it is resolved.  Thanks :)

**Comment by gschueler** [comment]
I'm curious: what did you discover as the cause?

**Comment by jjethwa** [comment]
@gschueler   The only change was the newer Rundeck release as the CLI and ec2 plugin are not updated.  The debug logs did not provide information when it was not working, so I don't have any more details.  Glad it's working now though 😄

**Comment by gschueler** [comment]
@jjethwa ok, weird, thanks for the follow up :)
