### ISSUE TITLE
ACL list is not parseable

### ISSUE THREAD

**Issue by plambert** [rundeck/rundeck-cli#149]
The output of `rd system acls list` is not parseable.  It contains ANSI codes even if not writing to a terminal.  It also puts the ANSI clear code `\e[0m` on the same line as the data.  And STDOUT mixes the actual list and non-list headers as well as an unnecessary blank line:

```
$ rd system acls list
\e[32m# 1 ACL Policy items for system
\e[0mexample-file.aclpolicy

```

The `# 1 ACL Policy items for system` should be written to STDERR, not STDOUT.

The `\e[0m` should be at the end of the previous line, before the newline.

The blank line at the end should go to STDERR, not STDOUT.

Other commands should work similarly.

Here're the tests to tell if this is working correctly:

1. Redirect STDERR to /dev/null and verify that exactly and only the data items are visible.  For example: `rd system acls list 2>/dev/null` should have no ANSI coloring, no heading or metadata lines, and no blank lines.

2. Pipe the command's STDOUT and STDERR through 'cat' and verify that no ANSI codes are sent.  For example, `rd system acls list 2>&1 | cat` should have no ANSI codes.

**Comment by gschueler** [comment]
is this still a problem if using those flags as mentioned above?
