### ISSUE TITLE
BulkDelete - allow noninteractive

### ISSUE THREAD

**Issue by mathieuchateau** [rundeck/rundeck-cli#184]
Hello,

I have 5 jobs that run every 5 minutes to gather apps logs & crash.

It generates a huge number of executions per monthes.

I wan to automate bulkdelete, hence without having to type "y".

Any way to do so ?

I tried echo y | ... but does not work

**Comment by gschueler** [comment]
Use the `-y`/`--confirm` flag

you can view command options via `rd executions deletebulk help`

HTH, please reopen if you have problems with it

**Comment by mathieuchateau** [comment]
I did not get that -y was the opposite of --confirm
thanks
