### ISSUE TITLE
Typo in `--logevel` option on `rd run`

### ISSUE THREAD

**Issue by puremourning** [rundeck/rundeck-cli#185]
The elaborated option for `-l` which sets the log level for `rd run` is `--logevel`.

```
     [--logevel -l /(verbose|info|warning|error)/] : Run the command using the specified LEVEL. LEVEL can be verbose, info, warning, error.
```

This seems like a typo of `--loglevel` ?

**Comment by gschueler** [comment]
good catch, thanks!

**Comment by gschueler** [comment]
also: using `--logevel verbose` does not seem to work correctly either o_O (execution is not in debug level)
