### ISSUE TITLE
Can't use 'rd run' with a job option starting with '@'

### ISSUE THREAD

**Issue by puremourning** [rundeck/rundeck-cli#186]
**Describe the bug**

`rd run` uses a special syntax for file attachments `@something`. This prevents using string options which start with `@`, like perforce labels.

**My Rundeck detail**

* Rundeck version: 2.10.2
* install type: rpm
* OS Name/version: RedHat 6.5
* DB Type/version: mysql
* RD - Rundeck API Client Tool (v1.0.22) -

**To Reproduce**
1. Create a job with a string option name Label
2. Try and execute the job with `rd run -p PROJECT -j JOB -- -Label @now`

**Expected behavior**
The job option should be set to the value '@now'

**Actual behaviour**
rd run fails with:

```
Input error for [run]: File Option -Label: File cannot be read: now
You can use: "run help" to get help.
```

**Additional context**

Perforce labels are identified as @labelname, @now meaning the head revision.

**Workaround**

As mentioned on https://github.com/rundeck/rundeck/issues/3590, the workaround is to `export RD_URL=http://server:port/api/17`. Confirmed this works.

**Comment by puremourning** [comment]
Further, as mentioned [here](https://github.com/rundeck/rundeck/issues/3443#issuecomment-401413559), the option doesn't enable debug mode when setting `--logevel verbose`

**Comment by gschueler** [comment]
some ideas for fixing this:

1. require a `\` before the `@` if it is the first char in the option value, e.g. `-Label \@now`
2. add a flag to the `run` command to disable `@value` interpretation as files for all of the options (or inversely disable it by default and add a flag to enable it)
3. remove `-option @file` processing, and require only `-option@ file` (which is already a feature)

**Comment by puremourning** [comment]
personally i would go for 3., because it is the most canonical, but i realise that's a breaking change. I feel 2 is better than 1 because then you end up with 'what about an option that starts with a \@' and '\\@' etc. sort of fiddliness to implement.

 I'm cool with any way to do it that works :)

**Comment by gschueler** [comment]
Ok I think I will go with 2 (avoiding breakage)

**Comment by puremourning** [comment]
Thanks!
