### ISSUE TITLE
Way to force fetch from git with SCM (Remote fetch command?)

### ISSUE THREAD

**Issue by mwvinzi** [rundeck/rundeck-cli#193]
Is there a command I can run to force fetch a git repository through the rd command or api so I can run the import command immediately after pushing to master? We have a pipeline where when we push changes to jobs in Gitlab, that it will kick off a pipeline and run the rd command to import jobs, but rundeck has not seen the diffs in the files yet so it doesn't do anything. Any ideas, or help would be appreciated.

**Comment by mwvinzi** [comment]
I guess what it is i'm looking for is a command to remote fetch before i do the import. Is there a command like that in cli or api?

**Comment by gschueler** [comment]
The SCM api lets you perform any of the actions provided by the git plugin.  If you list the actions available using the `rd projects scm status`, it should display `remote-pull` and `remote-fetch`.  You can perform one of those before the import using the `rd projects scm perform` command.  additionally, if you have "pull automatically" enabled, it will pull for you during the status check.
