### ISSUE TITLE
Encrypt password using CLI

### ISSUE THREAD

**Issue by outon** [rundeck/rundeck-cli#195]
I think that it could be posible to add an option to get easily an option to get encrypted, ofuscated or hashed password using CLI.

` rd users edit --user admin --encryptpwd admin`

Another option to enhance security could be that every time application starts if we have plain passwords on file realm.propierties encrypt them on the fly and save the file with encrypted passwords. 

So password are never stored on plain text

Before RunDeck is running : realm.property contains:
`admin:admin,user,admin,anvils`

After RunDeck startup realm.properties is modified to:
`admin: CRYPT:adpexzg3FUZAk,user,admin,anvils`

**Comment by gschueler** [comment]
@outon this sounds like a request for the https://github.com/rundeck/rundeck project.  Note that the Rundeck WAR launcher does now have a way to generate passwords, see the `--encryptpwd Jetty` option described here https://docs.rundeck.com/docs/administration/security/authenticating-users.html#propertyfileloginmodule
