### ISSUE TITLE
NullPointerException when execution has no Job

### ISSUE THREAD

**Issue by mveroone** [rundeck/rundeck-cli#202]
while running : `rd executions deletebulk -p wproject> --older 28d -y` i came upon this error : 

```
Exception in thread "main" java.lang.NullPointerException
	at org.rundeck.client.api.model.Execution.getInfoMap(Execution.java:97)
	at org.rundeck.client.tool.commands.Executions.lambda$outputExecutionList$12(Executions.java:569)
```

This line in the code does a  `getJob()`.  
But API reference (v23 or v27) speicifes that the fiels `<job>` is optional when querying for a list of executions.

that seems like a big bug and I can't understand how noone ever faced it before, although I couldn't find during my search

**Comment by mveroone** [comment]
I deleted the old executions on the UI and now, despite having jobless executions, it does not throw an exception anymore

**Comment by mveroone** [comment]
Funny as I have tested something, and it seems the client fails only if a format output is given (with `-% "blabla %id xyz"` . Without it, it won't try to get this non-existant id and will run correctly.

**Comment by mveroone** [comment]
This is nuts. It's not because noone had time to acknowledge this bug that it is stale or deserves to be closed ><

**Comment by gschueler** [comment]
sorry, the stale bot is a bit aggressive!! I will remove or disable it, i don't like that behavior!! @mveroone
