### ISSUE TITLE
rd-api-client lib should produce maven pom to allow publishing correctly to a maven repo

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck-cli#235]

**Comment by MatrixCrawler** [comment]
Why was that closed? I think this would be a good idea. Would love to use the api as a maven dependency in my tools.

**Comment by MatrixCrawler** [comment]
why was this closed?
I really would like to use the api in some of our tools and my life would be easier if it was a maven dependency.

**Comment by gschueler** [comment]
there is a way to use it as a java lib now from bintray via maven or gradle.  sorry, the documentation to do this was not merged yet, but is now available, see https://rundeck.github.io/rundeck-cli/javalib/
