### ISSUE TITLE
Passing Multivalue Options via rd

### ISSUE THREAD

**Issue by elioe** [rundeck/rundeck-cli#237]
I have a job where option “App_Pool” is multivalued with a space delimiter as follows: 

Foo-8080 Bar-8080 Quux-8080 

When I call another job via rd, I use this line: 

rd run --project ZZZ --follow --job ${JOB_GROUP}/Get_Member_States-Single_Server -- -F5_Device_Group ${DEVICE_GROUP} -Server ${SERVER_NAME} -App_Pool ""${POOLS[@]}"" 

The other job also accepts multivalue option “App_Pool,” and it works fine from the GUI. But when I run it from `rd,` it only sees the first option: 

Servers: testing 
Pools: xyz-1u39app.xxxxxxxx.com-8143 xyz-1u39app.xxxxxxxx.com-8243 xyz-1u39app.xxxxxxxx.com-8343 (these are the pools the parent job has defined) 
 Found matching job: xxxxxx-9c1a-433c-8a61-9c031d5ee849 App_Support/Java/F5/Prod/Get_Member_States-Single_Server 
 Execution started: [2793757] xxxxxx-9c1a-433c-8a61-9c031d5ee849 App_Support/Java/F5/Prod/Get_Member_States-Single_Server 
Pools: xyz-1u39app.xxxxxxxx.com-8143 (the second job only sees the first pool) 
Matched testing with 127.0.0.1 in f5 pool xyz-1u39app.xxxxxxx.com-8143. Pool member is 127.0.0.1:8143 
 Found matching job: xxxxxx-9525-4389-a80d-452e2566c134 App_Support/Java/F5/Prod/Get_Member_State 
 Execution started: [2793762] xxxxxx-9525-4389-a80d-452e2566c134 App_Support/Java/F5/Prod/Get_Member_State 
<snip/> 

How do I ensure that the parent job is passing all values of a multivalue option and that the second job is seeing them all? Thanks.

**Comment by gschueler** [comment]
can you try `-App_Pool "${POOLS[*]}"` ?

I think the shell expansion is resulting in a value that is not quoted as expected.  If you use `"${VAR[@]}"` this tells bash to requote each element of the array.  Using `"${VAR[*]}"` does not requote it.  This is the relevant section of the bash manual: https://www.gnu.org/software/bash/manual/html_node/Arrays.html#Arrays

>  If the subscript is ‘@’ or ‘\*’, the word expands to all members of the array name. These subscripts differ only when the word appears within double quotes. If the word is double-quoted, ${name[*]} expands to a single word with the value of each array member separated by the first character of the IFS variable, and ${name[@]} expands each element of name to a separate word. 

In this case you don't want to expand to separate "words" but as a single word, and set the IFS variable to space (i think that is the default)
