### ISSUE TITLE
rd run --quiet does not wait until execution is complete

### ISSUE THREAD

**Issue by sumeshpremraj** [rundeck/rundeck-cli#258]
Documentation for the quiet flag says:

```	
[--quiet -q] : Echo no output, just wait until the execution completes.
```

When I tried it, the command returned without waiting for the job to be complete (I verified it was still running via the rundeck GUI).

I ran the below command (some info is masked obviously):

```
ubuntu@host:~$ rd run -q -p Ops -j 'JobName' -- -Option "option value"
# Found matching job: d6a0e3b9-0b3c-407c-ba3a-ce39079caf1e JobName
# Execution started: [45779519] d6a0e3b9-0b3c-407c-ba3a-ce39079caf1e JobName <https://rundeck.domain.com/project/Project/execution/show/45779519>
```

I'm not sure if this is a bug or outdated description of the `-q` option. Please let me know if you need any more details/logs/output.

**Comment by gschueler** [comment]
i think you also need the `--follow` flag to wait until completion, the help text should be updated for the --quiet flag

**Comment by sumeshpremraj** [comment]
Yes, I tried the `-f` flag and got it working shortly after (the similarity with `tail` command helps!), I'll open a PR to update the help text.
