### ISSUE TITLE
rd cli config file is not used?

### ISSUE THREAD

**Issue by tsolodov** [rundeck/rundeck-cli#260]
Hi Guys.

What ma I doing wrong.

I installed rd cli on MacOS.

I created config file:
cat ~/.rd/rd.conf
RD_URL=https://xxx.yyy.zzzz:8443
RD_TOKEN=aaabbbzzz
RD_INSECURE_SSL=true

when   I run rd cli it still asks about rundeck url.
$ RD_DEBUG=1 RD_CONF=~/.rd/rd.conf ./bin/rd system info
Input error for [info]: Environment variable RD_URL is required: Please specify the Rundeck base URL, e.g. http://host:port or http://host:port/api/14
You can use: "info help" to get help.

Could you please advise?

**Comment by gschueler** [comment]
Try this:

~~~
export RD_URL=https://xxx.yyy.zzzz:8443
export RD_TOKEN=aaabbbzzz
export RD_INSECURE_SSL=true
~~~

**Comment by tsolodov** [comment]
If I export host/token it will work, but I want to use config file. Why it doesn't work? 

I used https://rundeck.github.io/rundeck-cli/install/#zip-install option.
My OS: Mojave.
Java: openjdk version "1.8.0_212"

**Comment by gschueler** [comment]
use `export` in the config file.  the config file is sourced by the cli tool script, so it is essentially the same as exporting those vars before executing it. see https://rundeck.github.io/rundeck-cli/configuration/#configuration

e.g. here is my `~/rd/rd.conf` file:

~~~ .sh
# ~/rd/rd.conf
export RD_URL=${RD_URL:-http://ecto1.local:4440}
export RD_COLOR=${RD_COLOR:-1}
~~~

it allows me to override it in my local shell as well

**Comment by tsolodov** [comment]
My bad. It works, please close the issue.
