### ISSUE TITLE
Custom attributes filtering using .* does not work when combined with other attributes

### ISSUE THREAD

**Issue by puremourning** [rundeck/rundeck-cli#267]
We are using `RD_FORMAT=json rd nodes list --project <p> --filter <f> --verbose` to extract some info from the nodes storage.

The filter in question is: `Fidessa:System: XTP8L_DEV Fidessa:Node: .* username: adia tags: fidserver`

However, this always returns empty. Investigation has shown that using `.*` as the filter value does not appear to match for custom attributes when combined with other filters.

here's some examples:

* `env RD_FORMAT=json rd nodes list --project XIT --filter 'Fidessa:Node: .*'` : returns a big list of stuff
* `env RD_FORMAT=json rd nodes list --project XIT --filter 'Fidessa:Node: .* tags: fidserver'` : returns `[]`
* `env RD_FORMAT=json rd nodes list --project XIT --filter 'Fidessa:Node: LONDON tags: fidserver'` : returns a (smaller) list of stuff

Clearly this is inconsistent. I found that if I did the following, it returned what was expected:

* `env RD_FORMAT=json rd nodes list --project XIT --filter 'Fidessa:Node: ".*" tags: fidserver'` : reutrns the right stuff

Note however, this is not a shell quoting issue as my `.*` is always passed directly as an argument to `rd`. Using `export RD_FORMAT=json` has the same result as well, so it's not to do with using `/usr/bin/env`.

**Comment by gschueler** [comment]
that's curious...i assume the same filter works in the GUI?

**Comment by gschueler** [comment]
are you still having this issue? I was unable to reproduce it.  the only variance i saw was when the server node cache was out of date with my defined nodes.

**Comment by puremourning** [comment]
Not sure. Will check maybe. I guess we implemented Some workaround and moved on.
