### ISSUE TITLE
rundeck-cli not honnoring RD_CONF settings on macos

### ISSUE THREAD

**Issue by fredleger** [rundeck/rundeck-cli#268]
Following the current doc for 1.7 i would expect that export RD_CONF=somefile.conf will use the variabales defined in this file to populate the cli context.

Experimenting arround showed that this is not the case at least on macosx:

```sh
16:40:40 ~/tmp/labs-rundeck-cli
➜ env | grep RD_CONF
RD_CONF=/Users/frederic/tmp/labs-rundeck-cli/rd.conf

16:40:42 ~/tmp/labs-rundeck-cli
➜ java -jar rundeck-cli-1.1.7-all.jar projects list
# WARNING: RD_INSECURE_SSL=true, no hostname or certificate trust verification will be performed
Input error for [list]: Environment variable RD_URL is required: Please specify the Rundeck base URL, e.g. http://host:port or http://host:port/api/14
You can use: "list help" to get help.

16:40:48 ~/tmp/labs-rundeck-cli
➜ cat $RD_CONF
export RD_URL=http://noexisting:4440
export RD_USER=admin
export RD_PASSWORD=admin
export RD_AUTH_PROMPT=false
#export RD_INSECURE_SSL=true
```

**Comment by gschueler** [comment]
Hi @fredleger , the RD_CONF usage depends on using the `rd` shell script which is included in the zip/rpm/deb packaging.  If you just use `java -jar` it won't be used.

Perhaps we should enhance it to use an actual conf file, which would also work on e.g. Windows OS

**Comment by fredleger** [comment]
Ok make sense then. I think this could be addressed through just a link to the script itself that i didn't find when wanting to download. The official site is taking you only to the jar.

Maybe a tarball with script + jar + README.md and other relevant resources/assets ?

**Comment by ShepTeck** [comment]
> Hi @fredleger , the RD_CONF usage depends on using the `rd` shell script which is included in the zip/rpm/deb packaging. If you just use `java -jar` it won't be used.
> 
> Perhaps we should enhance it to use an actual conf file, which would also work on e.g. Windows OS

Yes, can we please make this something to use on Windows. I took a while with the documentation to realize that in windows I now have to put either a token or a plain text username/password in environment variables to use the CLI tool; which is less than great.
