### ISSUE TITLE
Get the job execution id when running a job

### ISSUE THREAD

**Issue by sinister3vil** [rundeck/rundeck-cli#285]
Hello,

Is it possible to get the job execution id when running a job in a way that's scriptable, without needing to parse the output. Say, like an environment variable, so when the job ends jobExecId=1234 is accessible in the environment?

**Comment by gschueler** [comment]
it's not possible to automatically export the environment variable.  I can modify the `rd run` command to allow formatting the Execution info output similar to the `rd executions info` command.  you can use that in combination with the `RD_FORMAT=json`  or `-%` format option for better scripting

**Comment by sinister3vil** [comment]
Hello @gschueler 

Is this released in 1.3.2?

```
[11:45]kntouskos@SIN3MINT:scripts> rd run --id 0c636a77-2ad2-4b7b-b93a-d7a7ea4d6488 -- -Input 172.29.1.43 -Type IPs -% "%id"
# Execution started
11988 running 2020-08-14T11:45:35+0300 - http://172.16.0.11:4440/project/xxx/execution/show/11988 job 0c636a77-2ad2-4b7b-b93a-d7a7ea4d6488 test-job
```

**Comment by gschueler** [comment]
the `-%` needs to be placed before the `--` i think, try this:

    rd run --id 0c636a77-2ad2-4b7b-b93a-d7a7ea4d6488 -% "%id" -- -Input 172.29.1.43 -Type IPs

**Comment by sinister3vil** [comment]
@gschueler 

Yes, you are right. My bad.
Thanks for the fix.
