### ISSUE TITLE
Use RDECK_BASE var and locate etc/framework.properties authentication if available

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck-cli#29]
If `RDECK_BASE` is set, locate framework.properties to load RUNDECK_URL/RUNDECK_USER/RUNDECK_PASSWORD.

**Comment by ahonor** [comment]
I would like to remove this feature. I think this can be a problematic behavior. For example, I might be using `rd` for non admin related tasks and want to assume my own credentials are being used (as I also depend on ACLs for my particular user account). I am concerned that an `rd` user would effectively be automatically being logged in as "admin" when on the server and RDECK_BASE is set.

**Comment by gschueler** [comment]
will remove
