### ISSUE TITLE
Missing "all.jar" for v1.2.2

### ISSUE THREAD

**Issue by dandunckelman** [rundeck/rundeck-cli#291]
I assume this file should exist:

https://github.com/rundeck/rundeck-cli/releases/download/v1.2.2/rundeck-cli-1.2.2-all.jar

Or did something change to remove this going forward?

**Comment by gschueler** [comment]
i've been updating some of the build scripts, i will check on that, thanks

**Comment by dandunckelman** [comment]
I figured. No worries.

Please keep me posted.

**Comment by gschueler** [comment]
@dandunckelman should be available in 1.2.3

**Comment by dandunckelman** [comment]
Thanks @gschueler 

Already got it 👍
