### ISSUE TITLE
Ensure there is an 'scripting mode' on all the commands

### ISSUE THREAD

**Issue by luisfdez** [rundeck/rundeck-cli#3]
Hi @gschueler ,

I've been testing the new CLI and I think is looking very good and improves significantly the previous one.

I want to propose you to add to the TODO list an item like: ensure that all the commands have an scripting mode. This should ensure that there is a flag like `--output-format=yaml` that returns an scripting friendly output of the commands (and by default you have the human-readable one). For instance the `rd system` prints an output YAML compliant but it's not the case with `rd projects list`.

Having this option could help to do fancier stuff like intregation with tools like Puppet, etc...

What do you think?

**Comment by gschueler** [comment]
yes that is something I'd like to add, using json or yaml.

adding a feature like that to https://github.com/simplifyops/cli-toolbelt will be the way to it
