### ISSUE TITLE
get resources for a project

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck-cli#30]
New command that wraps [GET /api/14/project/[PROJECT]/resources](http://rundeck.org/docs/api/index.html#resourcesnodes)

Eg, get all the nodes tagged 'cuz':

```
rd projects resources -p my project --filter "tags: cuz" --format yaml
```

**Comment by gschueler** [comment]
already in there

**Comment by gschueler** [comment]
`rd nodes -p project --filter "tags: cuz"`
or
`RD_FORMAT=yaml rd nodes -p project --filter "tags: cuz"`

you can also just tack the filter on to the end of the commandline without a `--filter`:

`RD_FORMAT=yaml rd nodes -p project tags: cuz`

**Comment by ahonor** [comment]
LOL! How did i miss that? Great to hear it's done.

**Comment by gschueler** [comment]
i added yesterday
