### ISSUE TITLE
illegal reflective access operation with 1.3.2 and openjdk11

### ISSUE THREAD

**Issue by cova-fe** [rundeck/rundeck-cli#331]
I'm testing rd cli with openjdk11 and I'm seeing this issue, starting from 1.3.2. 1.3.1 is fine.
1.3.2 is fine with openjdk8

It is only a warning, but maybe useful to know.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/rundeck/bin/rundeck-cli.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by gschueler** [comment]
@cova-fe thanks, that is fixable

**Comment by Dany21000** [comment]
Hi, 

I've the same bug with openjdk 11.0.8.
I'm searching for a temporary workaround to hide the error message in shell script : just add a very poor `2>/dev/null` like `rd projects list  --outformat "%name" 2>/dev/null`

**Comment by gschueler** [comment]
we can add a jar manifest entry which quells this I believe. reference: https://github.com/square/retrofit/issues/3448
