### ISSUE TITLE
rd nodes adds a dash before each entry in rundeck 1.3.2

### ISSUE THREAD

**Issue by RolandVExp** [rundeck/rundeck-cli#332]
Maybe I missed something but previously, we were getting our nodes using thins kind of rd command:
`rd nodes -F 'node_envid:dev02 node_type:zoolx node_type:solx' -p reset-wklx -% "%nodename %node_type%node_instanceid"`

This gave us this output using version 1.3.1:
`velo1solx02-1.mycomp.com solx1`

Now with version 1.3.2:
`- velo1solx02-1.mycomp.com solx1`

I did not see anything about the extra dash in the changelog.

**Comment by gschueler** [comment]
i changed the formatting so that data from `-v` output would be nicer, but I didn't notice it was going to affect simple text lines like that.  I can revert it

**Comment by dginhoux** [comment]
Yes, i've the same problem.
I use RDCLI for generate "rd options json files".... everything is broken now.
