### ISSUE TITLE
"rd project set"  command fails ( error 500 ) in the first run if more than 3 parameters are used

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck-cli#346]
### How To Reproduce: 

**4 parameters** :shows error 500 only in the first run

```
$ rd projects create -p my_test_group9
# Created project: 
# 	my_test_group9
$

rd projects configure set -p my_test_group9 -- --project.globals.property1="test-value1" --project.globals.property2="test-value2" --project.description="Testing Group 1" --project.disable.executions="true" 
Error: (no message)

Request failed: 500 Server Error
$

$rd projects configure set -p my_test_group9 -- --project.globals.property1="test-value1" --project.globals.property2="test-value2" --project.description="Testing Group 1" --project.disable.executions="true" 
$ 

```
**Less than 3 parameters**:  always succeeds ( EXPECTED BEHAVIOR) 

```
$rd projects create -p my_test_group9
# Created project: 
# 	my_test_group9
$

$rd projects configure set -p my_test_group9 -- --project.globals.property1="test-value1" --project.globals.property2="test-value2" --project.description="Testing Group 1"
$

```

*** The same steps using "rd update" always succeeds.

**Comment by gschueler** [comment]
a 500 response indicates a server error, what are any error messages on the server console?

**Comment by sebastianbello** [comment]
@gschueler 

`[2021-02-18T15:13:17,409] ERROR StackTrace - Full Stack Trace:
groovy.lang.MissingMethodException: No signature of method: rundeck.services.FrameworkService.handleProjectSchedulingEnabledChange() is applicable for argument types: (com.dtolabs.rundeck.server.projects.RundeckProject, Boolean, Boolean...) values: [RundeckProject{config='RundeckProjectConfig{name='my_test_group9', lastModifiedTime=Thu Feb 18 15:13:17 CLST 2021}'}, ...]
Possible solutions: handleProjectSchedulingEnabledChange(java.lang.String, boolean, boolean, boolean, boolean)
	at org.codehaus.groovy.runtime

(.. snip..) 

2021-02-18T15:13:17,424] ERROR StackTrace - Full Stack Trace:
groovy.lang.MissingMethodException: No signature of method: rundeck.services.FrameworkService.handleProjectSchedulingEnabledChange() is applicable for argument types: (com.dtolabs.rundeck.server.projects.RundeckProject, Boolean, Boolean...) values: [RundeckProject{config='RundeckProjectConfig{name='my_test_group9', lastModifiedTime=Thu Feb 18 15:13:17 CLST 2021}'}, ...]
Possible solutions: handleProjectSchedulingEnabledChange(java.lang.String, boolean, boolean, boolean, boolean)
	at rundeck.controllers.ProjectController.apiProjectConfigPut(ProjectController.groovy:1479) ~[classes!/:?]
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223) ~[grails-core-4.0.3.jar!/:4.0.3]

(..snip..)

[2021-02-18T15:13:17,462] ERROR errors.GrailsExceptionResolver - MissingMethodException occurred when processing request: [PUT] /api/31/project/my_test_group9/config
No signature of method: rundeck.services.FrameworkService.handleProjectSchedulingEnabledChange() is applicable for argument types: (com.dtolabs.rundeck.server.projects.RundeckProject, Boolean, Boolean...) values: [RundeckProject{config='RundeckProjectConfig{name='my_test_group9', lastModifiedTime=Thu Feb 18 15:13:17 CLST 2021}'}, ...]
Possible solutions: handleProjectSchedulingEnabledChange(java.lang.String, boolean, boolean, boolean, boolean). Stacktrace follows:
groovy.lang.MissingMethodException: No signature of method: rundeck.services.FrameworkService.handleProjectSchedulingEnabledChange() is applicable for argument types: (com.dtolabs.rundeck.server.projects.RundeckProject, Boolean, Boolean...) values: [RundeckProject{config='RundeckProjectConfig{name='my_test_group9', lastModifiedTime=Thu Feb 18 15:13:17 CLST 2021}'}, ...]
Possible solutions: handleProjectSchedulingEnabledChange(java.lang.String, boolean, boolean, boolean, boolean)
	at rundeck.controllers.ProjectController.apiProjectConfigPut(ProjectController.groovy:1479) ~[classes!/:?]
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223) ~[grails-core-4.0.3.jar!/:4.0.3]

(..snip.. )`

Second run, works fine

**Comment by gschueler** [comment]
can you file the 500 error as a rundeck issue?

**Comment by gschueler** [comment]
as you noticed, the `rd` script seems to have a limitation with only 8 arguments passed to the input of the process.

as a workaround the `rd projects configure set` command can take a file input in json or properties format to set multiple properties
