### ISSUE TITLE
OKHttp upgrade to 4.9.x

### ISSUE THREAD

**Issue by sheinbergon** [rundeck/rundeck-cli#355]
Your OKHttp version is years old by now. It makes dependency conflicts a thing when trying to incorporate your rd-client-api inside other applications. Is there anything preventing you from upgrading it?

**Comment by gschueler** [comment]
prs welcome

**Comment by sheinbergon** [comment]
Achieved by using #357 https://github.com/rundeck/rundeck-cli/pull/357

**Comment by sheinbergon** [comment]
I see this is now properly released to maven central. Closing.
