### ISSUE TITLE
How do you install this on a Mac?

### ISSUE THREAD

**Issue by shreyasbharath** [rundeck/rundeck-cli#374]
Thanks for your work on this!

I've been trying to install this on my Mac and there's no homebrew formula. Do we have to install it manually?

**Comment by fdevans** [comment]
Sorry, there is not a homebrew formula for this.  The zip or standalone jar may work, but I don't know if we've tested specifically on Mac for this.

**Comment by MegaDrive68k** [comment]
Hi @shreyasbharath, the [local zip](https://rundeck.github.io/rundeck-cli/install/#zip-install) installation works like a charm on Mac :)

<img width="849" alt="Screen Shot 2021-11-25 at 10 30 58" src="https://user-images.githubusercontent.com/51376003/143450489-2e3dbc1e-a99f-4436-918a-0cb9fd369d5a.png">

Greetings!

**Comment by onizmx** [comment]
Me too
