### ISSUE TITLE
rd cli doesn't reveal tokens

### ISSUE THREAD

**Issue by Bilanda** [rundeck/rundeck-cli#379]
Hello, 

I'm having an issue with rundeck cli v1.3.11.
When i create a new API token, i can't reveal it with CLI. It always show "null".
Steps to reproduce : 

1. Run `rd tokens create -u <USER> -r user,admin -d 0d`
2. Get Token's ID with `rd tokens list -u github-actions`
3. Try to reveal it with `rd tokens reveal -i <ID>`
4. Get null value 

Screenshot : 

![image](https://user-images.githubusercontent.com/34126156/155357833-5527e8b0-80e5-4f9b-a8c1-d2a5d416b2d1.png)

**Comment by gschueler** [comment]
If you are using Rundeck 3.3.8 or later, the token is no longer available in cleartext after creation: https://docs.rundeck.com/docs/api/rundeck-api.html#get-a-token

**Comment by Bilanda** [comment]
Oh sorry my bad, i thought it was only unavailable with API but still with rd cli. 
I'm closing this issue, thanks for this quick reply
