### ISSUE TITLE
RD_PROMPT is not used

### ISSUE THREAD

**Issue by guhcampos** [rundeck/rundeck-cli#38]
The docs mention RD_PROMPT as an environment variable to suppress the client from asking for credentials. This is useful for using 'rd' in scripted environments.

Setting RD_PROMPT, however, leads to no changes. A quick search on the GitHub repository shows that while all the other environment variables such as RD_TOKEN and RD_USER are read in the beginning of the App.java source file, RD_PROMPT is never used anywhere in the code.

**Comment by gschueler** [comment]
wups

**Comment by gschueler** [comment]
documentation bug ;) should be `RD_AUTH_PROMPT`
