### ISSUE TITLE
bug: adhoc/jobs run --follow might return non-zero exit code before execution completes

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck-cli#39]
expected:

`adhoc --follow` should wait until execution is complete, and return 0/1 exit code based on execution status.

actual:

if log output completes before execution completes, follow mode will exit non-zero incorrectly

**Comment by shamil** [comment]
@gschueler I'm still experiencing this.
using version `1.0.5` and often get exit code 2 while in rundeck the execution is succeeded...
