### ISSUE TITLE
error response "Unexpected character"

### ISSUE THREAD

**Issue by ljmscx** [rundeck/rundeck-cli#4]
Hi guys,
i have some problems using the rundeck-cli tool. For example when i try the simple command
`rd system`
i get the following:

```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.InputStreamReader@8b96fde; line: 1, column: 2]
```

Here are my settings:
profile

```
-Drundeck.jetty.connector.forwarded=true
-Dserver.web.context=/rundeck
```

framework.properties

```
framework.server.name = rundeck
framework.server.hostname = my-internal-hostname.net
framework.server.port = 4440
framework.server.url = http://my-internal-hostname.net:4440/rundeck
# Username/password used by CLI tools.
framework.server.username = admin
framework.server.password = password
```

rundeck-config.properties
`grails.serverURL=https://my-external-hostname.net/rundeck`

also i'm setting the following enviroment variables
RUNDECK_USER=admin
RUNDECK_PASSWORD=password
RUNDECK_URL=http://my-internal-hostname.net:4440/rundeck

any ideas why it is not working?

**Comment by gschueler** [comment]
hmm, can you try doing `DEBUG=1 rd system` ? this will echo all of the HTTP traffic.

what version of Rundeck are you using?

Did you try using the external url in the RUNDECK_URL ?

**Comment by ljmscx** [comment]
hi, so the debug output is the following:

```
--> GET http://my-internal-hostname.net:4440/rundeck/api/16/system/info HTTP/1.1
<-- 403 Forbidden http://my-internal-hostname.net:4440/rundeck/api/16/system/info (59ms, unknown-length body)
--> GET http://my-internal-hostname.net:4440/rundeck/ HTTP/1.1
<-- 200 OK http://my-internal-hostname.net:4440/rundeck/user/login (19ms, unknown-length body)
--> POST http://my-internal-hostname.net:4440/rundeck/j_security_check HTTP/1.1 (43-byte body)
java.net.SocketTimeoutException: connect timed out
```

The error changed from `Unexpected character` to `connect timed out` after i removed the trailing slash from the RUNDECK_URL. I can't use the external url because the access is protected by some company access tool.
I'm running version 2.6.9-1

**Comment by gschueler** [comment]
is it possible to change to using an API token to test this?  This would require only 1 HTTP request instead of going through the username/password authentication flow.  The DEBUG output in that case will also have the entire HTTP content

**Comment by gschueler** [comment]
I think I may know the problem.  Because you have `grails.serverURL=https://my-external-hostname.net/rundeck`, the auth flow after `POST` will redirect to the `/menu/home` URL, but will be using the external hostname.  I.e. Rundeck request to `/` (after authentication) will redirect using the external URL.  At this point the auth flow will timeout because you cannot connect at to that hostname.

I will see if i can tweak the auth flow to accommodate that behavior

**Comment by gschueler** [comment]
I created a new release https://github.com/rundeck/rundeck-cli/releases/tag/v0.1.20

you can try this:

**Bypass an external URL**:

If your Rundeck server has a different *external URL* than the one you are accessing, you can tell the `rd` tool to treat redirects to that external URL as if they were to the original URL you specified.

	export RUNDECK_URL=http://internal-rundeck:4440/rundeck
	export RUNDECK_BYPASS_URL=https://rundeck.mycompany.com

This will rewrite any redirect to `https://rundeck.mycompany.com/blah`
as `http://internal-rundeck:4440/rundeck/blah`.

**Comment by gschueler** [comment]
also, has these new debug values:
`DEBUG=1` - basic http request debug
`DEBUG=2` - http headers
`DEBUG=3` - http body

**Comment by ljmscx** [comment]
@gschueler 
thanks for the fix, i will try it.

**Comment by gschueler** [comment]
closing, let me know if not fixed
