### ISSUE TITLE
RUN-1631: `--require` no longer treats 0 query results as failure 

### ISSUE THREAD

**Issue by shamil** [rundeck/rundeck-cli#468]
When I run command like 

```shell
rd executions deletebulk -R -y -m 20 --older 1d -p TestProject
```

It would return 2 if no results, and 0 if there are resutlts. In 2.x it always returns 0 now

**Comment by jplindquist** [comment]
Just ran into the same issue.  Looks like this stopped working in 2.0.0, possibly somewhere in [here](https://github.com/rundeck/rundeck-cli/compare/v1.4.3...v2.0.0#diff-d642ca4eed70d21d663ee8aacdd2df045fea7b221e4359ed4243bb8c9c2a4364L545-R586)?

Rolling back to 1.4.3 restores the previous functionality for the time being
