### ISSUE TITLE
Cannot use --include-webhooks or --regenerate-tokens with API < 34 (currently: 29)

### ISSUE THREAD

**Issue by xzizka** [rundeck/rundeck-cli#506]
Hello,
I have 2 systems:
- **old Rundeck:** AlmaLinux 9
- **new Rundeck:** Ubuntu 22.04.2

I am trying to export and import the complete project from one machine to another.   
I exported the project this way:
```
[root@almatest export]# rd system info | grep build
  build: 4.11.0-20230313
  buildGit: v4.11.0-0-gb588a16
[root@almatest export]# rd projects archives export -p test2 -f test2.jar -i=all
# Export Archive for project: test2
# Contents: [all]
# Begin asynchronous request...
.
# Wrote 238892 bytes of application/zip to file test2.jar
[root@almatest export]# 
```
Then I moved the JAR file to the machine where I want to import it.  
Then I performed the following:
```
root@rundeck1:/home/user1# rd system info | grep build
  build: 4.12.0-20230417
  buildGit: v4.12.0-0-g8273864
root@rundeck1:/home/user1# rd projects create -p test2
# Created project: 
#       test2
root@rundeck1:/home/user1# rd projects archives import -f ./test2.jar -p test2 -c -w
Cannot use --include-webhooks or --regenerate-tokens with API < 34 (currently: 29)
Usage: rd projects archives import [-acnrstwx] [--strict] -f=<file> -p=<project> [-I[=<components>...]]... [-O[=<String=String>...]]...
Import a project archive
...
```
I check both systems and I see that I use API version 44.  The goal is to migrate complete project including webhooks, that is why I uset the `-w` flag.  
Is there a way how to sort out this issue? Thanks.

**Comment by gschueler** [comment]
the rd-cli tool uses a certain API version internally by default for broader compatibility.  the error indicates that `--include-webhooks` requires API version 34+, so you must specify the API version to use via the `RD_URL` environment variable, e.g. `RD_URL=http://host:port/api/34`
