### ISSUE TITLE
`nodes list` ignores ACL and list all nodes which user is not supposed to see

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck-cli#52]
Version: 1.0.3
Install Type: rpm
OS: centos 7

# Steps to reproduce

`RD_USER=userA RD_PASSWORD=password rd nodes list`

# Expected Result

Only nodes which userA has privileges to see should be listed (as the case when user list nodes on rundeck UI)

# Actual Result

All nodes are listed, even for those which userA does not have privilege.

**Comment by gschueler** [comment]
hmm, curious i think this is a Rundeck bug!

**Comment by rophy** [comment]
Yes I think it's probably a critical bug with rundeck API.

**Comment by gschueler** [comment]
filed rundeck bug: https://github.com/rundeck/rundeck/issues/2265

**Comment by gschueler** [comment]
this should be fixed now in rundeck 2.7.2
