### ISSUE TITLE
[Request for Enhancement] : 'latest' or 'last' argument to fetch latest execution status of a job 

### ISSUE THREAD

**Issue by mramanathan** [rundeck/rundeck-cli#53]
## Current usage:

To know the latest status of execution for a given job, this works:

    rd executions -p <project-name> -i <job-UUID> -m 1

In the current setup, I feel, it's left to the user to _check the execution number (and output) from the above command against the job execution number in rundeck UI to ensure this is "indeed" the latest_ job.

## Request:

    rd executions -p <project0name> -i <job-UUID> -m <last | latest>

'last' or 'latest' can be supplied as a tag or fixed value. 

This way end-user running the query is aware that the CLI does return the status of the latest execution for the given project / job combination.

**Comment by gschueler** [comment]
hmm, if you don't specify an offset (`-o/--offset`) and status (`-s/--status`) then it will implicitly be the latest completed execution result.

perhaps we could add `--latest` or something to default to `--max 1 --offset 0`

**Comment by mramanathan** [comment]
It seems omitting _(-o/--offset)_ and _(-s/--status)_ arguments to the query as well returns the result of latest executed rundeck job ?

**Comment by gschueler** [comment]
note: `-m 1` achieves the same thing
