### ISSUE TITLE
Running projects scm action -i import -a import-all has no effect

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck-cli#62]
Version: 1.0.5-1
Type: RPM

Steps to reproduce
```shell
[tsaiyl@lsc102 ~]$ rd projects scm status -i import
synchState: IMPORT_NEEDED
message: 1 file(s) need to be imported
actions:
  import-all


[tsaiyl@lsc102 ~]$ rd projects scm perform -i import -a import-all
# Action import-all was successful.
# Result: SCM import Action was Successful: import-all
[tsaiyl@lsc102 ~]$ rd projects scm status -i import
synchState: IMPORT_NEEDED
message: 1 file(s) need to be imported
actions:
  import-all
```

Expected result:  after running import-all, syncState should be `CLEAN`

Actual result: after runing import-all, syncState remains `IMPORT_NEEDED`

**Comment by gschueler** [comment]
you should run `rd projects scm inputs -i import -a import-all` and view the inputs required, which I think will indicate you need to specify what "items" (files) to import.  Those values will have to be specified in the `--fields` or `--item` arguments to `scm perform -i import -a import-all`

**Comment by rophy** [comment]
Thanks for the info.  It seems `projects scm inputs -i import -a import-all` only list of items, and does not show `which items are out of sync`.  Is there a way to obtain this info, or a way to specify "select all"?

**Comment by gschueler** [comment]
I think the API can be updated to include a flag for items which are considered out of sync: that information is available from the plugin, and is used to automatically select items in the GUI for import, but it is not passed through to the API yet.

**Comment by gschueler** [comment]
...to clarify, this requires an update to Rundeck API

**Comment by gschueler** [comment]
@gonzales-ott-bot that's another issue, i will file it: https://github.com/rundeck/rundeck-cli/issues/99

**Comment by lcardito** [comment]
Hi @gschueler thanks for this.

Do we have a reference for the Rundeck API update needed for this?

**Comment by gschueler** [comment]
@lcardito for the rundeck API improvement, here is the issue: https://github.com/rundeck/rundeck/issues/2330

**Comment by jodylarsen** [comment]
why isn't the correct behavior for --action import-all to import all changes?  Adding a requirement to list out individual jobs to import seems unnecessarily using --fields or --item seem unnecessarily complex.

**Comment by Wambosa** [comment]
i was about to create a new issue for this, but just stumbled on this thread. I'll post my path to reproduce anyways and +1 this. i spent my evening yesterday and most of this morning confused by the verbiage "import-all". Additionally i tried to use "remote-pull", but it seems like you cannot skip actions.

I understand that this could be addressed at the API level first. I'll take a look at the plugin real quick to see if anything has developed.

```
rd projects create -p ops
rd projects configure set -p ops --file ~/project.properties
rd keys create --type privateKey --path keys/lib/rundeck/.ssh/github_rsa --file ~/github_rsa
rd projects scm setup -p ops --integration import --type git-import --file ~/scm-import.json
rd projects scm perform -p ops -i import --action initialize-tracking -f useFilePattern="true" filePattern=".*\\.yaml"

#the import all will respond with false positive success, and not actually do anything
rd projects scm perform -i import -p ops --action import-all

#this one works and gives the same success message as the prior command
rd projects scm perform -i import -p ops --action import-all --item "ops/my-job-file.yaml"
```

**Comment by gschueler** [comment]
fyi: this flag was added to `rd projects scm perform`: `--allitems`

See https://github.com/rundeck/rundeck-cli/pull/134

**Comment by tsaiyl** [comment]
@gschueler So glad to see this addressed! Since we talked about updating API, Is there a required specific rundeck version for this to work?

**Comment by gschueler** [comment]
@tsaiyl no, it uses 2 api calls instead and does not require any change on the server

**Comment by madcrokodile** [comment]
working command now is
rd projects scm perform -i import -p MyProject --action import-all --allitems
