### ISSUE TITLE
No option to accept self-signed SSL certificates

### ISSUE THREAD

**Issue by nkadel-skyhook** [rundeck/rundeck-cli#63]
It can be very awkward, and expensive, to generate signed SSL certificates for Rundeck test environments. I'd like to be able to tell the "rd" command that it's OK to accept a self-signed certificate, at least for specifically designated hosts, but I'm having some difficulty finding the best way to allow this without laboriously creating my own personal .jks for every developer or admin who might need to test my server with me.

**Comment by nkadel-skyhook** [comment]
Is there a timetable on when a fresh RPM build will be available with this patch?

**Comment by gschueler** [comment]
I am doing some more fixes and will make a new release later today

**Comment by oCHRISo** [comment]
Can you let us know when you have a new release and what version it is?

**Comment by gschueler** [comment]
it is in the latest release, 1.0.7
