### ISSUE TITLE
run command fails with exit code 2, while succeeded in rundeck

### ISSUE THREAD

**Issue by shamil** [rundeck/rundeck-cli#65]
I think it's related to https://github.com/rundeck/rundeck-cli/issues/39
> using `rundeck-cli` version: `1.0.5`

**Comment by gschueler** [comment]
is this running a job, or an adhoc command?

Can you run using `RD_DEBUG=3` to capture all of the http responses?

I'm primarily interested in the final response when this occurs for an execution.

example:

~~~{.json}
 {"id":"715","offset":"539","completed":true,"execCompleted":true,"hasFailedNodes":false,"execState":"succeeded","lastModified":"1486057830000","execDuration":30459,"percentLoaded":98.89908256880734,"totalSize":545,"entries":[{"time":"09:50:00","absolute_time":"2017-02-02T17:50:00Z","log":"the time is *boing*","level":"NORMAL","user":"greg","command":null,"stepctx":"1","node":"ecto1.local"},{"time":"09:50:00","absolute_time":"2017-02-02T17:50:00Z","log":"Thu Feb  2 09:50:00 PST 2017","level":"NORMAL","user":"greg","command":null,"stepctx":"1","node":"ecto1.local"}]}
~~~

**Comment by shamil** [comment]
Here is the final response, when I get exit code `2`

```json
{
  "id": "233855",
  "offset": "0",
  "completed": false,
  "message": "Pending",
  "execCompleted": false,
  "hasFailedNodes": false,
  "execState": "scheduled",
  "execDuration": -115,
  "entries": []
}
```

**Comment by shamil** [comment]
And yes, I run a specific job not `adhoc` command

**Comment by gschueler** [comment]
huh, ok thanks

**Comment by gschueler** [comment]
can you paste your full `rd` commandline when you run the job?

**Comment by shamil** [comment]
`rd run --project Tasks --job "Backup DB" -f -- -type full -clear`

**Comment by gschueler** [comment]
that's very strange.  the `execState: scheduled` indicates it has a start date in the future, which would occur if you use the `-@/--at` commandline flag to schedule it, but hopefully not happen if you ask it to run immediately.

I was able to reproduce it using `-@`, so I will fix the issue if it has not started yet
