### ISSUE TITLE
"rd" command should allow selection of config file

### ISSUE THREAD

**Issue by nkadel-skyhook** [rundeck/rundeck-cli#72]
Thanks for adding the "APP_CONFIG" file, it's useful.

I've noticed that the APP_CONFIG file is fairly hardcoded to $HOME/.$APP_NAME/$APP_NAME.conf . This makes it quite difficult to select an alternate configuration to speak with a distinct Rundeck server or distinct credentials in an automated fashion. I'd be happy to submit a patch to use "getopts" and support a "-c configfile"option if it's welcome. Alternatively, the various hardcoded values in the rd shell script can use this kind of structure.

  DEFAULT_JVM_OPTS="${DEFAULT_JVM_OPTS:-"
  APP_CONFIG=${APP_CONFIG:-$HOME/.$APP_NAME/$APP_NAME.conf}

and the like. I'd want to set APP_CONFIG to be a more rundeck specific variable to avoid overlap. And I'll be happy to submit a patch for whichever is preferred.

**Comment by gschueler** [comment]
something like this would probably be best:

    APP_CONFIG=${RD_CONF_FILE:-$HOME/.$APP_NAME/$APP_NAME.conf}

Might as well change `APP_CONFIG` to be RD_CONF_FILE as well

**Comment by nkadel-skyhook** [comment]
I like it. Do you need a pull request for it?

**Comment by gschueler** [comment]
sure, that would be helpful, thank you

**Comment by gschueler** [comment]
ping @nkadel-skyhook wondering if you were able to make this change, thanks

**Comment by gschueler** [comment]
closing due to lack of interest, please reopen if you would like, thanks.

**Comment by isuftin** [comment]
I would very much like to see this implemented as it would allow me to have my single Rundeck instance work against multiple remote Rundeck instances.
