### ISSUE TITLE
support for new file type option?

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck-cli#78]
Is the new file type option supported by rundeck-cli?

**Comment by gschueler** [comment]
@rophy yes it will be, once Rundeck 2.8 is released I will merge changes to support Rundeck API v19, and support file uploads.  so you can do something like `rd run -j <job> -- -file1 @somefile`

**Comment by rophy** [comment]
@gschueler  I have created a local 2.8-SNAPSHOT build which is working perfectly. 

Are the rundeck-cli changes already available in some forks? I can help to test if they are.

**Comment by gschueler** [comment]
@rophy https://github.com/rundeck/rundeck-cli/pull/79

**Comment by gschueler** [comment]
@rophy has the file upload been working for you on that branch?

**Comment by rophy** [comment]
@gschueler briefly tested in win7 and centos, worked great!

The `@` notation is not obvious, and has a small impact on linux:

In bash shell, without `@` notation, the following path would expand to /home/tsaiyl/testing.bat:
```
java -jar rundeck-cli-1.0.9-SNAPSHOT-all.jar  run -p GSSC -j 'common/windows/Run Batch' -F CRTVM0023 -- -BatchFile ~/testing.bat
```

With requiring the `@` prefix, path expansion would not work:

```
java -jar rundeck-cli-1.0.9-SNAPSHOT-all.jar  run -p GSSC -j 'common/windows/Run Batch' -F CRTVM0023 -- -BatchFile @~/testing.bat
# Found matching job: 7f1cd7ac-a657-4b08-8b44-22a0ade01d34 common/windows/Run Batch
Input error for [run]: File Option -BatchFile: File cannot be read: ~/testing.bat
You can use: "run help" to get help.
```

But it's nothing big deal. Thanks a lot for all the great work!

**Comment by gschueler** [comment]
@rophy ok, I was imitating cUrl in the `@path` syntax.  I can add an alternate syntax which would support the path expansion in the shell, like: `-BatchFile@ ~/testing.bat`
