### ISSUE TITLE
Problem creating/updating keys using files

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck-cli#9]
Using a command like this to create a key password storage

rd keys create --path keys/some/path --type password --file key.password

There are no errors thrown, but the password key that is created, which I know to be a good password, results in failure when I use it in a job step.

I also can use the --prompt option with "rd keys create" to manually enter the password on the command-line, and that seems to work.

This leads me to believe that there is some issue with echoing a password string to a file, then passing it in using the --file option.

**Comment by gschueler** [comment]
using a file for input to password type should remove any newlines at the end
