### ISSUE TITLE
Rundeck CLI version in PowerShell

### ISSUE THREAD

**Issue by lw-schick** [rundeck/rundeck-cli#93]
I would appreciate it to have a PowerShell CLI for Rundeck which f.e communicates with rundeck via the API.

**Comment by gschueler** [comment]
We have a list of Rundeck API client libraries and tools here: [List of Rundeck API clients](http://rundeck.org/news/2017/05/01/list-of-rundeck-api-clients.html) If a powershell version is created we will update that list.

For now, closing this issue as it does not pertain to the Java client tool.
