### ISSUE TITLE
Manage nodes

### ISSUE THREAD

**Issue by mengesb** [rundeck/rundeck-cli#94]
Currently only the 'read' (CRUD) operation of nodes exists today via the command list. Need to add support for create, update, and delete nodes.

In the mean time, I recommend updating the static text to 'List node resources' instead of 'List and manage node resources' - there's no management of any kind of node resources in rd currently.

**Comment by gschueler** [comment]
The "List and manage node resources" text was aspirational, I guess 😄 The rundeck API does not really support CUD features for nodes yet.
