### ISSUE TITLE
V1.0.11-1 not compatible with API v19

### ISSUE THREAD

**Issue by hoofdcoach** [rundeck/rundeck-cli#95]
Hi,

So the return values in API V19 have changed and the rundeck-cli is not working well with it.

When I configure to use the API v18 (export RD_URL==http://192.168.42.16:4440/api/18), it somehow still doesn't work.

```
$ rd tokens create -u admin
Credentials for URL: http://192.168.42.16:4440/api/18
Enter username (blank for token auth): admin
Enter password:
# API Token created:
null
```

 I tried debugging and I got these lines:

`INFO: <-- 403 Forbidden http://192.168.42.16:4440/api/18/tokens/admin(10ms)
`
Odd: if I remove my username from the url I see 5 tokens, when I add it it returns 0...

`INFO: {"error":true,"apiversion":19,"errorCode":"unauthorized","message":"(unauthenticated) is not authorized for: /api/18/tokens/admin"}
`

Why is it saying apiversion:19 ?

```
INFO: {"user":"admin","token":"aokIyvDUvjkZNdOjarrhACo7iARQK4MJ"}
May 03, 2017 9:44:22 AM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP (59-byte body)
```

This is the end of the debug, API code is created but on my terminal I still see: null.

**Comment by gschueler** [comment]
thanks for the report. It looks like there was a bug introduced in Rundeck 2.8.0 which incorrectly uses the API v19 response for API v18 requests for token creation.  v18 is supposed to include a `id` field (the token value), where v19 changed to call it `token`.  The response is including `token` in both cases, which `rd` is not expecting.

I can update `rd` to handle the (invalid) response, but I also filed an issue for Rundeck here:  https://github.com/rundeck/rundeck/issues/2479

**Comment by hoofdcoach** [comment]
Wauw, a big thank you for fixing this so quick!
